name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  cloud_firestore: ^3.1.5
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
